---
title: "MA_Hw_05_01"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
---

## Packages
```{r}
library(plyr)
library(rethinking)
library(rstan)
library(tidyverse)
library(ggplot2)
library(MASS)
library(xtable)
library(invgamma)
```

## Data-processing
### Read data
```{r}
data("rugged")
rugged
```

### Full_df & Without_Sey_df
Form two dataframe, one for all data, and another for data without Seychelles
```{r}
full_data <- rugged %>%
  dplyr::select(country, rgdppc_2000, cont_africa, rugged) %>% 
  mutate(AR = cont_africa*rugged)
full_data <- full_data[complete.cases(full_data),] #complete.cases for selecting non-NA row
data_without_sey <- full_data %>% filter(country != "Seychelles")
data_without_sey
```

### Standardlization
```{r}
full_data = full_data %>% 
  mutate(
    log_gdp = log(rgdppc_2000)) %>% 
  mutate(
    log_gdp_std = log_gdp / mean(log_gdp),
    rugged_std = rugged / max(rugged))

data_without_sey = data_without_sey %>% 
  mutate(
    log_gdp = log(rgdppc_2000)) %>% 
  mutate(
    log_gdp_std = log_gdp / mean(log_gdp),
    rugged_std = rugged / max(rugged))

full_data
data_without_sey
```

###Data for use 
```{r}
q1_data = list(N = nrow(data_without_sey),
                  y = log(data_without_sey$rgdppc_2000),
                  A = data_without_sey$cont_africa,
                  R = data_without_sey$rugged,
                  AR = data_without_sey$AR)
q1_data
```

##Part A 
### Gibbs sampling
#### Prepare
```{r}
# beta_0 hyper parameters (known)
m0<-5
t0<-1

m1<-5
t1<-1

m2<-5
t2<-1

m3<-5
t3<-1

a<-.5 # shape
g<-.7 # scale

n<-length(q1_data$y)
A = q1_data$A
R = q1_data$R
AR = q1_data$AR

tphi<-rinvgamma(1, shape=a, rate=g)
tb0<-rnorm(1, m0, sqrt(t0) )
tb1<-rnorm(1, m1, sqrt(t1) )
tb2<-rnorm(1, m2, sqrt(t2) )
tb3<-rnorm(1, m3, sqrt(t3) )
tphi; tb0; tb1; tb2; tb3;

y<-rnorm(n, tb0 + tb1*A + tb2*R + tb3*AR, sqrt(tphi))


#### Functions for grid evaluation of posterior densities

rb0cond<-function(y, A,R,AR, b1, b2, b3, phi, t0, m0){
  grid<-seq(-10,10,.001)
  
  p<-numeric(length=length(grid))
  for(i in 1:length(p) ){
    p[i]<- (-(1/(2*phi))*sum( (y - (grid[i]+b1*A+b2*R+b3*AR))^2 ))  + ( -(1/(2*t0))*(grid[i] - m0)^2)
  }
  
  draw<-sample(grid, size = 1, prob = exp(1-p/max(p)))
  return(draw)
}

rb1cond<-function(y, A,R,AR, phi, t1, m1, b0, b2, b3){
  grid<-seq(-10,10,.001)
  
  p<-numeric(length=length(grid))
  for(i in 1:length(p)){
    p[i]<- (-(1/(2*phi) )*sum( (y - (b0+grid[i]*A+b2*R+b3*AR))^2 )) + ( -(1/(2*t1) )*(grid[i] - m1)^2)
  }
  
  draw<-sample(grid, size = 1, prob = exp(1-p/max(p)))
  return(draw)
}

rb2cond<-function(y, A,R,AR, phi, t1, m1, b0, b1, b3){
  grid<-seq(-10,10,.001)
  
  p<-numeric(length=length(grid))
  for(i in 1:length(p)){
    p[i]<- (-(1/(2*phi) )*sum( (y - (b0+b1*A+grid[i]*R+b3*AR))^2 )) + ( -(1/(2*t1) )*(grid[i] - m1)^2)
  }
  
  draw<-sample(grid, size = 1, prob = exp(1-p/max(p)))
  return(draw)
}

rb3cond<-function(y, A,R,AR, phi, t1, m1, b0, b1, b2){
  grid<-seq(-10,10,.001)
  
  p<-numeric(length=length(grid))
  for(i in 1:length(p)){
    p[i]<- (-(1/(2*phi) )*sum( (y - (b0+b1*A+b2*R+grid[i]*AR))^2 )) + ( -(1/(2*t1) )*(grid[i] - m1)^2)
  }
  
  draw<-sample(grid, size = 1, prob = exp(1-p/max(p)))
  return(draw)
}


#### Implement Gibbs Sampling

iter<-1000
burnin<-101
phi<-b0<-b1<-b2<-b3<-numeric(iter)
phi[1]<-b0[1]<-b1[1]<-b2[1]<-b3[1]<-6

for(i in 2:iter ){
  phi[i]<-rinvgamma(1, shape = (n/2 + a), rate = .5*sum( (y - (b0[i-1]+b1[i-1]*A+b2[i-1]*R+b3[i-1]*AR))^2 ) + g  )
  b0[i]<-rb0cond(y, A,R,AR, b1[i-1],b2[i-1],b3[i-1], phi[i], t0, m0)
  b1[i]<-rb1cond(y, A,R,AR, phi[i], t1, m1, b0[i],b2[i-1],b3[i-1])
  b2[i]<-rb2cond(y, A,R,AR, phi[i], t2, m2, b0[i],b1[i],b3[i-1])
  b3[i]<-rb3cond(y, A,R,AR, phi[i], t3, m3, b0[i],b1[i],b2[i])
}
```

#### Visualize Results
```{r}
par(mfrow=c(3,2))
plot(phi[burnin:iter],type='l'); abline(h=tphi, col='red')
plot(b0[burnin:iter],type='l'); abline(h=tb0, col='red')
plot(b1[burnin:iter],type='l'); abline(h=tb1, col='red')
plot(b2[burnin:iter],type='l'); abline(h=tb0, col='red')
plot(b3[burnin:iter],type='l'); abline(h=tb1, col='red')
```

##Part B
### Metropolis within Gibbs example
```{r}
n = length(q1_data$y)
x = q1_data$y 
n.rep = 20000


a <- 1; b <- .1; c <- 0; d <- 100
mu <- 0; phi <- 1
n.accept <- 0

thetamg = matrix(0, 2, n.rep)
thetamg[,1] <- c(mu,phi)
for (j in 2:n.rep) {
    mup = mu + rnorm(1)*0.8 ## proposal for mu
    log.a = sum(dnorm(x, mup, sqrt(phi), log=TRUE)) +
    dnorm(mup, c, sqrt(d), log=TRUE) -
    sum(dnorm(x, mu, sqrt(phi), log=TRUE)) -
    dnorm(mu, c, sqrt(d), log=TRUE)
    
    if (runif(1) < exp(log.a)) { ## MH accept?
      mu = mup
      n.accept = n.accept + 1
    }
## Gibbs update of phi...
    phi = 1/rgamma(1,
                   n/2+a,
                   sum((x-mu)^2)/2+b)
    thetamg[,j] = c(mu,phi) ## store results
}
```

### Plot
I drop the first 1000 times iterations because they are not stable enough yet
```{r}
layout(matrix(c(1,2,1,2,3,4),2,3))
plot(1001:n.rep, thetamg[1,-(1:1000)], type="l", xlab = "iteration",
     ylab = expression(mu))
plot(1001:n.rep, thetamg[2,-(1:1000)], type="l", xlab = "iteration",
     ylab = expression(sigma))
hist(thetamg[1,-(1:1000)], main = "",xlab = expression(mu))
hist(thetamg[2,-(1:1000)], main = "",
     xlab = expression(sigma))
```




