```{r}
library(rethinking)
library(rstan)
library(tidyverse)
```

```{r}
data(Howell1)
raw_data = Howell1

str(raw_data)
weight = raw_data$weight
height = raw_data$height

#mean(raw_data$height)

lr.model="
data{
    int n;
    vector[n] x;
    vector[n] y;
}
parameters{
    real alpha;
    real<lower = 0> beta1;
    real sigma;
}
model{
    vector[n] mu;
    alpha ~ normal(178,100);
    beta1 ~ normal(0,100);
    sigma ~ uniform(0,50);
    
    mu = alpha + beta1*x ;
    y ~ normal(mu, sigma);
}
generated quantities{
    real predict_y[n];
    vector[n] mu;

    mu = alpha + beta1*x;
    predict_y = normal_rng(mu, sigma);

}"

lr.data = list(
  n = nrow(raw_data),
  x = log(weight),
  y = height
)

lr.fit = stan(
  model_code = lr.model,
  data = lr.data,
  chain = 2,
  cores = 2,
  iter = 1000
)

lr.post = as.data.frame(lr.fit)
```

```{r}
predict_mu = lr.post %>% select(contains("mu"))

CI = data.frame(
  weight = raw_data$weight,
  mean= predict_mu %>% apply(., 2, mean),
  L_HPDI = predict_mu %>% apply(., 2, HPDI) %>% .[1,],
  U_HPDI = predict_mu %>% apply(., 2, HPDI) %>% .[2,]
)

predict_y = lr.post %>% select(contains("predict_y"))

PI = data.frame(
  weight = raw_data$weight,
  mean= predict_y %>% apply(., 2, mean),
  L_HPDI = predict_y %>% apply(., 2, HPDI) %>% .[1,],
  U_HPDI = predict_y %>% apply(., 2, HPDI) %>% .[2,]
)

```


```{r}
q2_answer_b_pic = ggplot()+
  geom_point(data=CI, aes(weight, height), color="red", alpha=0.1)+
  geom_line(data=CI, aes(weight,mean))+
  geom_ribbon(
    data = CI, aes(x=weight, ymin=L_HPDI, ymax=U_HPDI),
    fill="blue", alpha=0.4)+
  geom_ribbon(data = PI, aes(x=weight, ymin=L_HPDI, ymax=U_HPDI), alpha=0.2)+
  ggtitle("89% CI vs PI")

q2_answer_b_pic
```


