```{r}
library(rethinking)
library(rstan)
library(tidyverse)
```

```{r}
data(Howell1)
raw_data = Howell1

weight = raw_data$weight
height = raw_data$height

#mean(raw_data$height)

lr.model="
data{
    int n;
    vector[n] x;
    vector[n] y;
}
parameters{
    real alpha;
    real<lower = 0> beta1;
    real sigma;
}
model{
    vector[n] mu;
    alpha ~ normal(156,100);
    beta1 ~ lognormal(0,10);
    sigma ~ uniform(0,50);
    
    mu = alpha + beta1*x ;
    y ~ normal(mu, sigma);
}
generated quantities{
    real predict_y[n];
    vector[n] mu;

    mu = alpha + beta1*x;
    predict_y = normal_rng(mu, sigma);

}"

lr.data = list(
  n = nrow(raw_data),
  x = weight,
  y = height
)

lr.fit = stan(
  model_code = lr.model,
  data = lr.data,
  chain = 2,
  cores = 2,
  iter = 1000
)

lr.post = as.data.frame(lr.fit)
```

```{r}
testing_weight=c(46.95, 43.72, 64.78, 32.59, 54.63)
testing_weight = as.data.frame(testing_weight)

testing_predict_height = testing_weight %>% apply(
  ., 1, function(x) rnorm(
    n = nrow(lr.post),
    mean = lr.post$alpha + lr.post$beta1 * x,
    sd = lr.post$sigma
    )
  )

mean = apply(testing_predict_height, 2, mean)
testing_predict_HPDI = apply(testing_predict_height, 2, HPDI, prob = 0.89)

q1_answer_a = tibble(
  "Individual"= seq(1,5),
  "Weight"= testing_weight[,1],
  "Expected height"= mean,
  "lower 89% interval"= testing_predict_HPDI[1,1:5],
  "upper 89% interval"= testing_predict_HPDI[2,1:5]
)  

q1_answer_a
```

```{r}
intercept = lr.post$beta1
intercept_mean = mean(intercept)
intercept_mean = intercept_mean*10

q1_answer_b = intercept_mean
q1_answer_b
```


```{r}
predict_mu = lr.post %>% select(contains("mu"))

CI = data.frame(
  weight = raw_data$weight,
  mean= predict_mu %>% apply(., 2, mean),
  L_HPDI = predict_mu %>% apply(., 2, HPDI) %>% .[1,],
  U_HPDI = predict_mu %>% apply(., 2, HPDI) %>% .[2,]
)

predict_y = lr.post %>% select(contains("predict_y"))

PI = data.frame(
  weight = raw_data$weight,
  mean= predict_y %>% apply(., 2, mean),
  L_HPDI = predict_y %>% apply(., 2, HPDI) %>% .[1,],
  U_HPDI = predict_y %>% apply(., 2, HPDI) %>% .[2,]
)

q1_answer_c = ggplot()+
  geom_point(data=CI, aes(weight, height), color="red", alpha=0.1)+
  geom_line(data=CI, aes(weight,mean))+
  geom_ribbon(data = CI, aes(x=weight, ymin=L_HPDI, ymax=U_HPDI), alpha=0.4)+
  geom_ribbon(data = PI, aes(x=weight, ymin=L_HPDI, ymax=U_HPDI), alpha=0.2)+
  ggtitle("89% CI vs PI")

q1_answer_c
```

